name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, windows-11-arm, ubuntu-24.04-arm]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update && sudo apt-get install -y cmake make g++

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install cmake make

    - if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure project
      run: |
        cmake -S . -B build

    - name: Build project (Release)
      run: |
        cmake --build build --config Release

    - name: Run executable (Windows)
      if: runner.os == 'Windows'
      run: .\build\Release\DivToMulti.exe

    - name: Run executable (Linux/macOS)
      if: runner.os != 'Windows'
      run: ./build/DivToMulti